version: "3"
services:
  http-server:
    image: python:3.7-slim
    command: python3 -m http.server --bind 0.0.0.0
    volumes:
      - ./test.json:/test.json
      - ./test-bug.json:/test-bug.json
  filebeat:
    depends_on: 
      - http-server
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes: 
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro